# Generated by Django 5.1.6 on 2025-02-08 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('legal', 'Yuridik'), ('personal', 'Jismoniy')], default='personal', max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=13, null=True)),
                ('amount', models.IntegerField()),
                ('org_name', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('moderation', 'Moderatsiya'), ('approved', 'Tasdiqlangan'), ('cancelled', 'Bekor qilingan')], default='new', max_length=20)),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('plastic_card', 'Plastik karta'), ('transfer', "Pul o'tkazmasi")], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('bachelor', 'Bakalavr'), ('master', 'Magister')], default='bachelor', max_length=200)),
                ('contract_amount', models.IntegerField(default=0)),
                ('allocated_amount', models.IntegerField(default=0, null=True)),
                ('phone', models.CharField(max_length=13)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sponsor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.university'),
        ),
    ]
